language: julia
sudo: required
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
notifications:
  email: false
branches:
  only:
  - master
  - /release-.*/
  - /v(\d+)\.(\d+)\.(\d+)/
addons:
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("VegaLite"); Pkg.test("VegaLite"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("VegaLite")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  - julia -e 'cd(Pkg.dir("VegaLite")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - $TESTCMD -e 'cd(Pkg.dir("VegaLite")); include(joinpath("docs", "make.jl"))'
