site_name:        VegaLite.jl
repo_url:         https://github.com/fredo-dedup/VegaLite.jl
site_description: Julia bindings to the Vega-Lite visualization library.
site_author:      fredo-dedup

theme: readthedocs

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code

docs_dir: 'build'

pages:
  - Introduction: index.md
  - Quick Tour: quick.md
  - Global settings: global.md
  - Outputs: output.md
  - API reference: functions.md
